try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
